/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Model.Address;
import Model.Person;
import Model.PersonDirectory;
import java.awt.CardLayout;
import java.util.Date;

/**
 *
 * @author mansi kamble
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory pplDirectory;
    
    private Address homeAdd1;
    private Address homeAdd2;
    private Address homeAdd3;
    private Address homeAdd4;
    private Address homeAdd5;
    private Address homeAdd6;
    
    private Address workAdd1;
    private Address workAdd2;
    private Address workAdd3;
    private Address workAdd4;
    private Address workAdd5;
    private Address workAdd6;
   
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.pplDirectory = new PersonDirectory();
        
        this.homeAdd1 = new Address();
        this.workAdd1 = new Address();
        
        this.homeAdd2 = new Address();
        this.workAdd2 = new Address();
        
        this.homeAdd3 = new Address();
        this.workAdd3 = new Address();
        
        this.homeAdd4 = new Address();
        this.workAdd4 = new Address();
        
        this.homeAdd5 = new Address();
        this.workAdd5 = new Address();
        
        this.homeAdd6 = new Address();
        this.workAdd6 = new Address();
        
        generateDemoData();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        btnMngWorkArea = new javax.swing.JButton();
        workAreaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setBackground(new java.awt.Color(0, 0, 153));

        btnMngWorkArea.setBackground(new java.awt.Color(153, 204, 255));
        btnMngWorkArea.setText("Open Manager Work Area");
        btnMngWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngWorkAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnMngWorkArea)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnMngWorkArea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topPanel);

        workAreaPanel.setBackground(new java.awt.Color(197, 223, 249));
        workAreaPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngWorkAreaActionPerformed
        // TODO add your handling code here:
        ProfileMngWorkAreaJPanel panel = new ProfileMngWorkAreaJPanel(workAreaPanel, pplDirectory);
        workAreaPanel.add("ProfileMngWorkArea", panel);
        
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);

    }//GEN-LAST:event_btnMngWorkAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngWorkArea;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        
        Date date = new Date();
        
        //Adding Person 1 data
        
        Person p = pplDirectory.addPerson();
        p.setFirstName("Mansi");
        p.setLastName("Kamble");
        p.setSsn(998209822);
        p.setAge(24);
        p.setSalary(Double.valueOf("100000"));
        p.setCreditScore(Double.valueOf("740"));
        p.setFieldCreation(date);
        
        homeAdd1.setStreetAddress("898 Huntington Avenue");
        homeAdd1.setUnitNumber(7);
        homeAdd1.setCity("Boston");
        homeAdd1.setState("MA");
        homeAdd1.setZipCode(12345);
        homeAdd1.setPhoneNumber("9953357283");
        
        p.setHomeAddress(homeAdd1);
        
        workAdd1.setStreetAddress("35 Massachusetts avenue");
        workAdd1.setUnitNumber(3);
        workAdd1.setCity("Boston");
        workAdd1.setState("MA");
        workAdd1.setZipCode(12345);
        workAdd1.setPhoneNumber("3342537685");
        
        p.setWorkAddress(workAdd1);
        
        //Adding Person 2 Data
        
        p = pplDirectory.addPerson();
        p.setFirstName("Mason");
        p.setLastName("Harrison");
        p.setSsn(887753409);
        p.setAge(28);
        p.setSalary(Double.valueOf("120000"));
        p.setCreditScore(Double.valueOf("760"));
        p.setFieldCreation(date);
        
        homeAdd2.setStreetAddress("74 Medford");
        homeAdd2.setUnitNumber(10);
        homeAdd2.setCity("Cambridge");
        homeAdd2.setState("MA");
        homeAdd2.setZipCode(11225);
        homeAdd2.setPhoneNumber("8856753456");
        
        p.setHomeAddress(homeAdd2);
        
        workAdd2.setStreetAddress("39 Barbara avenue");
        workAdd2.setUnitNumber(21);
        workAdd2.setCity("Boston");
        workAdd2.setState("MA");
        workAdd2.setZipCode(12345);
        workAdd2.setPhoneNumber("5659873456");
        
        p.setWorkAddress(workAdd2);
        
        //Adding Person 3 Data
        
        p = pplDirectory.addPerson();
        p.setFirstName("Lisa");
        p.setLastName("Payne");
        p.setSsn(485982599);
        p.setAge(25);
        p.setSalary(Double.valueOf("100700"));
        p.setCreditScore(Double.valueOf("690"));
        p.setFieldCreation(date);
        
        homeAdd3.setStreetAddress("34 Clamden Street");
        homeAdd3.setUnitNumber(5);
        homeAdd3.setCity("Boston");
        homeAdd3.setState("MA");
        homeAdd3.setZipCode(12345);
        homeAdd3.setPhoneNumber("6712239875");
        
        p.setHomeAddress(homeAdd3);
        
        workAdd3.setStreetAddress("871 Maine Street");
        workAdd3.setUnitNumber(8);
        workAdd3.setCity("Palmer");
        workAdd3.setState("MA");
        workAdd3.setZipCode(11532);
        workAdd3.setPhoneNumber("9238572356");
        
        p.setWorkAddress(workAdd3);
        
        //Adding Person 4 Data
        
        p = pplDirectory.addPerson();
        p.setFirstName("Ryan");
        p.setLastName("Gosling");
        p.setSsn(654583290);
        p.setAge(30);
        p.setSalary(Double.valueOf("230000"));
        p.setCreditScore(Double.valueOf("780"));
        p.setFieldCreation(date);
        
        homeAdd4.setStreetAddress("30 Jamaica Plain");
        homeAdd4.setUnitNumber(1);
        homeAdd4.setCity("Boston");
        homeAdd4.setState("MA");
        homeAdd4.setZipCode(12345);
        homeAdd4.setPhoneNumber("9325813455");
        
        p.setHomeAddress(homeAdd4);
        
        workAdd4.setStreetAddress("Heath Street");
        workAdd4.setUnitNumber(2);
        workAdd4.setCity("Winthrop");
        workAdd4.setState("MA");
        workAdd4.setZipCode(15342);
        workAdd4.setPhoneNumber("3458345249");
        
        p.setWorkAddress(workAdd4);
        
        //Adding Person 5 Data
        
        p = pplDirectory.addPerson();
        p.setFirstName("Jenna");
        p.setLastName("Campbell");
        p.setSsn(575694253);
        p.setAge(22);
        p.setSalary(Double.valueOf("93000"));
        p.setCreditScore(Double.valueOf("710"));
        p.setFieldCreation(date);
        
        homeAdd5.setStreetAddress("30 Huntington Avenue");
        homeAdd5.setUnitNumber(11);
        homeAdd5.setCity("Amherst");
        homeAdd5.setState("MA");
        homeAdd5.setZipCode(13021);
        homeAdd5.setPhoneNumber("98672239516");
        
        p.setHomeAddress(homeAdd5);
        
        workAdd5.setStreetAddress("39 Massachusetts avenue");
        workAdd5.setUnitNumber(6);
        workAdd5.setCity("Amherst");
        workAdd5.setState("MA");
        workAdd5.setZipCode(13021);
        workAdd5.setPhoneNumber("3257042043");
        
        p.setWorkAddress(workAdd5);
        
        //Adding Person 6 Data
        
        p = pplDirectory.addPerson();
        p.setFirstName("Frida");
        p.setLastName("Kohl");
        p.setSsn(328957467);
        p.setAge(32);
        p.setSalary(Double.valueOf("240000"));
        p.setCreditScore(Double.valueOf("783"));
        p.setFieldCreation(date);
        
        homeAdd6.setStreetAddress("22 Malden Street");
        homeAdd6.setUnitNumber(9);
        homeAdd6.setCity("Cambridge");
        homeAdd6.setState("MA");
        homeAdd6.setZipCode(11225);
        homeAdd6.setPhoneNumber("9845234715");
        
        p.setHomeAddress(homeAdd6);
        
        workAdd6.setStreetAddress("254 Maine street");
        workAdd6.setUnitNumber(4);
        workAdd6.setCity("Cambridge");
        workAdd6.setState("MA");
        workAdd6.setZipCode(11225);
        workAdd6.setPhoneNumber("5699565706");
        
        p.setWorkAddress(workAdd6);
           
    }
}
