/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author mansi kamble
 */
public class ProfileMngWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel workAreaPanel;
    PersonDirectory pplDirectory;

    /**
     * Creates new form ProfileMngWorkAreaJPanel
     */
    public ProfileMngWorkAreaJPanel(JPanel workArea,PersonDirectory directory) {
        initComponents();
        this.workAreaPanel = workArea;
        pplDirectory = directory; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePerson = new javax.swing.JButton();
        btnListPerson = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 223, 249));

        btnCreatePerson.setBackground(new java.awt.Color(0, 0, 153));
        btnCreatePerson.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreatePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnListPerson.setBackground(new java.awt.Color(0, 0, 153));
        btnListPerson.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnListPerson.setText("List Person ");
        btnListPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListPerson)
                    .addComponent(btnCreatePerson))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreatePerson, btnListPerson});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListPerson)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel panel = new CreatePersonJPanel(workAreaPanel, pplDirectory);
        workAreaPanel.add("CreatePersonJPanel", panel);
        
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);   
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnListPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel panel = new ManagePersonJPanel(workAreaPanel, pplDirectory);
        workAreaPanel.add("ManagePersonJPanel", panel);
        
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);  
    }//GEN-LAST:event_btnListPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnListPerson;
    // End of variables declaration//GEN-END:variables
}
