/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Address;
import Model.Person;
import Model.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mansi kamble
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    
    JPanel workAreaPanel;
    PersonDirectory pplDirectory;
    private Person person;

    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel workArea,PersonDirectory directory, Person person) {
        initComponents();
        this.workAreaPanel = workArea;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSSN = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        HomeAddressPanel = new javax.swing.JPanel();
        txtStreetAddressHome = new javax.swing.JTextField();
        lblStreetAddressHome = new javax.swing.JLabel();
        txtCityHome = new javax.swing.JTextField();
        lblCityHome = new javax.swing.JLabel();
        txtZipHome = new javax.swing.JTextField();
        lblZipHome = new javax.swing.JLabel();
        txtUnitNumberHome = new javax.swing.JTextField();
        lblUnitNumberHome = new javax.swing.JLabel();
        txtStateHome = new javax.swing.JTextField();
        lblStateHome = new javax.swing.JLabel();
        txtPhoneNumberHome = new javax.swing.JTextField();
        lblPhoneNumberHome = new javax.swing.JLabel();
        WorkAddressPanel = new javax.swing.JPanel();
        txtStreetAddressWork = new javax.swing.JTextField();
        lblStreetAddressWork = new javax.swing.JLabel();
        txtUnitNumberWork = new javax.swing.JTextField();
        lblUnitNumberWork = new javax.swing.JLabel();
        txtCityWork = new javax.swing.JTextField();
        lblCityWork = new javax.swing.JLabel();
        txtStateWork = new javax.swing.JTextField();
        lblStateWork = new javax.swing.JLabel();
        txtZipWork = new javax.swing.JTextField();
        lblZipWork = new javax.swing.JLabel();
        txtPhoneNumberWork = new javax.swing.JTextField();
        lblPhoneNumberWork = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        txtCreditScore = new javax.swing.JTextField();
        lblCreditScore = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 223, 249));

        lblSSN.setText("SSN");

        HomeAddressPanel.setBackground(new java.awt.Color(183, 202, 239));
        HomeAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblStreetAddressHome.setText("Street Address");

        lblCityHome.setText("City");

        lblZipHome.setText("Zip Code");

        lblUnitNumberHome.setText("Unit Number");

        lblStateHome.setText("State");

        lblPhoneNumberHome.setText("Phone Number");

        javax.swing.GroupLayout HomeAddressPanelLayout = new javax.swing.GroupLayout(HomeAddressPanel);
        HomeAddressPanel.setLayout(HomeAddressPanelLayout);
        HomeAddressPanelLayout.setHorizontalGroup(
            HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeAddressPanelLayout.createSequentialGroup()
                        .addComponent(lblZipHome)
                        .addGap(32, 32, 32)
                        .addComponent(txtZipHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberHome)
                        .addGap(32, 32, 32)
                        .addComponent(txtPhoneNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeAddressPanelLayout.createSequentialGroup()
                        .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStreetAddressHome)
                            .addComponent(lblCityHome))
                        .addGap(32, 32, 32)
                        .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeAddressPanelLayout.createSequentialGroup()
                                .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStateHome)
                                .addGap(32, 32, 32)
                                .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeAddressPanelLayout.createSequentialGroup()
                                .addComponent(txtStreetAddressHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUnitNumberHome)
                                .addGap(32, 32, 32)
                                .addComponent(txtUnitNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        HomeAddressPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCityHome, lblPhoneNumberHome, lblStateHome, lblStreetAddressHome, lblUnitNumberHome, lblZipHome, txtCityHome, txtPhoneNumberHome, txtStateHome, txtStreetAddressHome, txtUnitNumberHome, txtZipHome});

        HomeAddressPanelLayout.setVerticalGroup(
            HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeAddressPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddressHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetAddressHome)
                    .addComponent(txtUnitNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnitNumberHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityHome)
                    .addComponent(txtStateHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipHome)
                    .addComponent(txtPhoneNumberHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumberHome))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        WorkAddressPanel.setBackground(new java.awt.Color(183, 202, 239));
        WorkAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblStreetAddressWork.setText("Street Address");

        lblUnitNumberWork.setText("Unit Number");

        lblCityWork.setText("City");

        lblStateWork.setText("State");

        lblZipWork.setText("Zip Code");

        lblPhoneNumberWork.setText("Phone Number");

        javax.swing.GroupLayout WorkAddressPanelLayout = new javax.swing.GroupLayout(WorkAddressPanel);
        WorkAddressPanel.setLayout(WorkAddressPanelLayout);
        WorkAddressPanelLayout.setHorizontalGroup(
            WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAddressPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkAddressPanelLayout.createSequentialGroup()
                        .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCityWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnitNumberWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStreetAddressWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreetAddressWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnitNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(WorkAddressPanelLayout.createSequentialGroup()
                        .addComponent(lblStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WorkAddressPanelLayout.createSequentialGroup()
                        .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhoneNumberWork, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblZipWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZipWork, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        WorkAddressPanelLayout.setVerticalGroup(
            WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAddressPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreetAddressWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreetAddressWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnitNumberWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStateWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WorkAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumberWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumberWork))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        lblLastName.setText("Last Name");

        lblAge.setText("Age");

        lblFirstName.setText("First Name");

        lblSalary.setText("Salary");

        lblCreditScore.setText("Credit Score");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person Details");

        btnBack.setBackground(new java.awt.Color(0, 0, 153));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(">>>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 153));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(btnUpdate))
                            .addComponent(HomeAddressPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(WorkAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtSSN))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCreditScore, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCreditScore, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(545, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomeAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFirstName)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLastName))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSSN)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAge))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSalary)
                        .addComponent(txtCreditScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCreditScore))
                    .addContainerGap(309, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Date date = new Date();
        
        int pSSN, pAge, pHomeUnit, pHomeZip, pHomePhone, pWorkUnit, pWorkZip, pWorkPhone;
        Double pSalary, pCreditScore;
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String ssn = txtSSN.getText();
        String age = txtAge.getText();
        String salary = txtSalary.getText();
        String creditScore = txtCreditScore.getText();
        
        String homeStreetAdd = txtStreetAddressHome.getText();
        String homeUnitNumber = txtUnitNumberHome.getText();
        String homeCity = txtCityHome.getText();
        String homeState = txtStateHome.getText();
        String homeZipCode = txtZipHome.getText();
        String homePhone = txtPhoneNumberHome.getText();
        
        String workStreetAdd = txtStreetAddressWork.getText();
        String workUnitNumber = txtUnitNumberWork.getText();
        String workCity = txtCityWork.getText();
        String workState = txtStateWork.getText();
        String workZipCode = txtZipWork.getText();
        String workPhone = txtPhoneNumberWork.getText();
        
        if("".equals(firstName.trim()) || "".equals(lastName.trim()) || "".equals(ssn.trim()) || 
                "".equals(age.trim()) || "".equals(salary.trim()) || "".equals(creditScore.trim())) {
            JOptionPane.showMessageDialog(this, "Enter All Personal Details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else if("".equals(homeStreetAdd.trim()) || "".equals(homeUnitNumber.trim()) || "".equals(homeCity.trim()) || 
                "".equals(homeState.trim()) || "".equals(homeZipCode.trim()) || "".equals(homePhone.trim())) {
            JOptionPane.showMessageDialog(this, "Enter All Home Address Fields", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(workStreetAdd.trim()) || "".equals(workUnitNumber.trim()) || "".equals(workCity.trim()) || 
                "".equals(workState.trim()) || "".equals(workZipCode.trim()) || "".equals(workPhone.trim())) {
            JOptionPane.showMessageDialog(this, "Enter All Work Address Fields", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                pSSN = Integer.parseInt(ssn);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "SSN is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pAge = Integer.parseInt(age);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Age is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pSalary = Double.valueOf(salary);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Salary is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pCreditScore = Double.valueOf(creditScore);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Credit Score is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pHomeUnit = Integer.parseInt(homeUnitNumber);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Home Unit Number is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pHomeZip = Integer.parseInt(homeZipCode);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Home Zip Code is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pHomePhone = Integer.parseInt(homePhone);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Home Phone Number is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pWorkUnit = Integer.parseInt(workUnitNumber);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Work Unit Number is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pWorkZip = Integer.parseInt(workZipCode);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Work Zip Code is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                pWorkPhone = Integer.parseInt(workPhone);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Work Phone Number is a Numeric Value", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Address homeAddress = new Address();
            Address workAddress = new Address();
            
            person.setFirstName(firstName);
            person.setLastName(lastName);
            person.getSsn();
            person.setAge(pAge);
            person.setSalary(pSalary);
            person.setCreditScore(pCreditScore);
            person.setFieldCreation(date);
            
            homeAddress.setStreetAddress(homeStreetAdd);
            homeAddress.setUnitNumber(pHomeUnit);
            homeAddress.setCity(homeCity);
            homeAddress.setZipCode(pHomeZip);
            homeAddress.setPhoneNumber(homePhone);
            
            person.setHomeAddress(homeAddress);
            
            workAddress.setStreetAddress(workStreetAdd);
            workAddress.setUnitNumber(pWorkUnit);
            workAddress.setCity(workCity);
            workAddress.setState(workState);
            workAddress.setZipCode(pWorkZip);
            workAddress.setPhoneNumber(workPhone);
            
            person.setWorkAddress(workAddress);
            
            JOptionPane.showMessageDialog(this, "Person Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            setViewMode();
            
            refreshTextFields();
   
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        workAreaPanel.remove(this);
        
        Component[] panelStack = workAreaPanel.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length -1];
        
        ManagePersonJPanel managePersonJPanel = (ManagePersonJPanel) lastPanel;
        managePersonJPanel.populateTable();
        
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.previous(workAreaPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeAddressPanel;
    private javax.swing.JPanel WorkAddressPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityHome;
    private javax.swing.JLabel lblCityWork;
    private javax.swing.JLabel lblCreditScore;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumberHome;
    private javax.swing.JLabel lblPhoneNumberWork;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStateHome;
    private javax.swing.JLabel lblStateWork;
    private javax.swing.JLabel lblStreetAddressHome;
    private javax.swing.JLabel lblStreetAddressWork;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnitNumberHome;
    private javax.swing.JLabel lblUnitNumberWork;
    private javax.swing.JLabel lblZipHome;
    private javax.swing.JLabel lblZipWork;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityHome;
    private javax.swing.JTextField txtCityWork;
    private javax.swing.JTextField txtCreditScore;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumberHome;
    private javax.swing.JTextField txtPhoneNumberWork;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStateHome;
    private javax.swing.JTextField txtStateWork;
    private javax.swing.JTextField txtStreetAddressHome;
    private javax.swing.JTextField txtStreetAddressWork;
    private javax.swing.JTextField txtUnitNumberHome;
    private javax.swing.JTextField txtUnitNumberWork;
    private javax.swing.JTextField txtZipHome;
    private javax.swing.JTextField txtZipWork;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSSN.setText(Integer.toString(person.getSsn()));
        txtAge.setText(Integer.toString(person.getAge()));
        txtSalary.setText(Double.toString(person.getSalary()));
        txtCreditScore.setText(Double.toString(person.getCreditScore()));
        txtStreetAddressHome.setText(person.getHomeAddress().getStreetAddress());
        txtUnitNumberHome.setText(Integer.toString(person.getHomeAddress().getUnitNumber()));
        txtCityHome.setText(person.getHomeAddress().getCity());
        txtStateHome.setText(person.getHomeAddress().getState());
        txtZipHome.setText(Integer.toString(person.getHomeAddress().getZipCode()));
        txtPhoneNumberHome.setText(person.getHomeAddress().getPhoneNumber());
        txtStreetAddressWork.setText(person.getWorkAddress().getStreetAddress());
        txtUnitNumberWork.setText(Integer.toString(person.getWorkAddress().getUnitNumber()));
        txtCityWork.setText(person.getWorkAddress().getCity());
        txtStateWork.setText(person.getWorkAddress().getState());
        txtZipWork.setText(Integer.toString(person.getWorkAddress().getZipCode()));
        txtPhoneNumberWork.setText(person.getWorkAddress().getPhoneNumber());
      
    }

    private void setViewMode() {
       txtFirstName.setEnabled(false);
       txtLastName.setEnabled(false);
       txtSSN.setEnabled(false);
       txtAge.setEnabled(false);
       txtSalary.setEnabled(false);
       txtCreditScore.setEnabled(false);
       txtStreetAddressHome.setEnabled(false);
       txtUnitNumberHome.setEnabled(false);
       txtCityHome.setEnabled(false);
       txtStateHome.setEnabled(false);
       txtZipHome.setEnabled(false);
       txtPhoneNumberHome.setEnabled(false);
       txtStreetAddressWork.setEnabled(false);
       txtUnitNumberWork.setEnabled(false);
       txtCityWork.setEnabled(false);
       txtStateWork.setEnabled(false);
       txtZipWork.setEnabled(false);
       txtPhoneNumberWork.setEnabled(false);
       
       btnSave.setEnabled(false);
       btnUpdate.setEnabled(true);
       
       
    }

    private void setEditMode() {
       txtFirstName.setEnabled(true);
       txtLastName.setEnabled(true);
       txtSSN.setEnabled(true);
       txtAge.setEnabled(true);
       txtSalary.setEnabled(true);
       txtCreditScore.setEnabled(true);
       txtStreetAddressHome.setEnabled(true);
       txtUnitNumberHome.setEnabled(true);
       txtCityHome.setEnabled(true);
       txtStateHome.setEnabled(true);
       txtZipHome.setEnabled(true);
       txtPhoneNumberHome.setEnabled(true);
       txtStreetAddressWork.setEnabled(true);
       txtUnitNumberWork.setEnabled(true);
       txtCityWork.setEnabled(true);
       txtStateWork.setEnabled(true);
       txtZipWork.setEnabled(true);
       txtPhoneNumberWork.setEnabled(true);
       
       btnSave.setEnabled(true);
       btnUpdate.setEnabled(false);
    }
}
